- binprot/parser.go
- binprot/respond.go
- client/binprot/headers.go
- client/binprot/prot.go
- client/blast.go
- client/common/types.go
- client/textprot/prot.go
- common/datatypes.go
- local/localComm.go
- local/localHandlers.go
- memproxy.go
- textprot/parser.go
- textprot/respond.go
Batch gets are native to the text protocol, but not to the binary protocol. An optimization for binary communication is to send a batch of gets as a pipelined set of GETQ commands, followed by either a final GET or a NOOP in order to guarantee a response. This branch implements this optimization in the binary protocol parser.
As well, there were numerous bugs found on the way, including issue #9, that needed to be fixed. Some bugs were there before the branch and have been found through testing. The internal representation of gets had to be changed a bit, which is why there's some changes in the text protocol package as well.
In order to test the new functionality, the blast script has been updated to send batch gets as well as get, set, delete, and touch commands. The implementation has …
> Binary batch get

- binprot/commands.go
- binprot/parser.go
- binprot/respond.go
- client/binprot/prot.go
- client/blast.go
- client/common/types.go
- client/textprot/prot.go
- common/datatypes.go
- local/localComm.go
- local/localHandlers.go
- memproxy.go
- textprot/respond.go
Get-and-touch command implemented. The GAT command only exists in the binary protocol, so the abstraction isn't quite perfect. The text parser will never return a GAT command, and the responder panics if it gets one.
Testing at this point has revealed a very rare bug with sets causing inconsistent state, but that is outside the purview of this branch. 
This pull request will close #16
> Cmd get and touch

- local/localComm.go
- local/localHandlers.go
- memproxy.go
- stream/chunkedLimitedReader.go
* Using buffo.ReadWriter instead of separate reader and writer
* More terse variables
* Use of Discard() instead of setting up limited readers
* Idiomatic if statements / error checking
> Cleaning up local IO interfaces

- client/binprot/prot.go
- client/blast.go
- client/common/types.go
- client/common/utils.go
- client/f/flags.go
- client/stats/stats.go
- client/textprot/prot.go
Added a bunch of improvements after instrumenting the blast script.
* -pprof flag to profile the testing application
* Moved back to bufio
* Got rid of lock contention by using separate rand instances
* Print fancy histograms per-command after testing complete
> Blast telemetry and improvements

- binprot/commands.go
- binprot/parser.go
- binprot/respond.go
- binprot/types.go
- common/datatypes.go
- handlers/memcached/chunked/handler.go
- handlers/memcached/chunked/localComm.go
- handlers/memcached/std/handler.go
- handlers/memcached/std/localComm.go
- memproxy.go
- metrics/counters.go
- metrics/endpoint.go
- textprot/parser.go
- textprot/respond.go
This takes care of issue #29 - Implement Counters 
The contents of this pull request is not only the counters implementation itself, but the use of them across the codebase to track everything we might need to debug an issue.
The implementation itself is fairly straightforward: A map of string key to uint64 pointer. The uint64 is operated on by the sync/atomic primitives that can atomically add a specified amount to a uint64. A sync.RWMutex is used to ensure no concurrent map alterations with the reads, but all reads are allowed concurrently. The atomic functions allow counters to be very quick - they take a negligible amount of time in the runtime of the program even under load.
Counters include the number of all operations and the high-level results of all those operations, the number …
> WIP - Counters

- common/datatypes.go
- handlers/memcached/chunked/handler.go
- handlers/memcached/chunked/localComm.go
- memproxy.go
- metrics/counters.go
* Faster metrics: No map access anymore. The registration function
returns an identifier that is used in the other functions. The
identifier is just an array index now instead of a map access.
* More metrics: chunked handler has metrics for misses because of
missing metadata, missing chunks, and bad token values.
> Faster counters, adding more metrics

- binprot/commands.go
- binprot/parser.go
- binprot/respond.go
- binprot/types.go
- client/binprot/prot.go
- client/blast.go
- client/common/types.go
- client/textprot/prot.go
- common/datatypes.go
- handlers/memcached/chunked/handler.go
- handlers/memcached/std/handler.go
- handlers/types.go
- memproxy.go
- textprot/parser.go
- textprot/respond.go
Implementing add across all parts of the application. This included the text and binary protocol parsers and responders, the chunked and standard local handlers, the common package constants, and the main memproxy file. The blast client load tester also implements add now as a part of the operations it uses to test.
> Add command

- binprot/commands.go
- binprot/parser.go
- binprot/respond.go
- binprot/types.go
- common/datatypes.go
- handlers/memcached/chunked/handler.go
- handlers/memcached/std/handler.go
- handlers/types.go
- textprot/respond.go
Adding a GetE command as a protocol extension. This command will not be recognized by Rend explicitly, but will be used to communicate with the L2 cache. When the L2 cache responds, the expiry time will come along with the response, allowing Rend to put the object into the L1 cache with the proper TTL. The portions of Rend which are reused by the L2 database have been updated to support a GetE command, including binary protocol parsing and responding, the handler interface, and some common package constants.
CC @smadappa @vuzilla @senugula
> GetE command

- binprot/respond.go
- common/datatypes.go
- handlers/memcached/constructors.go
- handlers/types.go
- memproxy.go
- orcas/l1l2.go
- orcas/l1only.go
- server/listen.go
- server/types.go
- textprot/parser.go
- textprot/respond.go
This pull request contains some *unfinished* L1 / L2 code! That particular code is not meant to be run in production yet. The args exist for L1 / L2 in the main program, but should not be used at this point. 
The purpose of this pull request is to merge the rest of the code base that has evolved around the server and handler composition. This is mainly to support other internal Netflix projects that are reusing this code. The driving use case has given a reason to clean up the admittedly leaky abstractions that existed before.
There's a few important bits:
* Handlers are now responsible for creating their own connection to the backend they handle.
* `HandlerConstConst` is a new type of constructor that returns a `HandlerConst` (constructor for a Handler). This generally returns a closure …
> Refactor level 3

- handlers/memcached/chunked/handler.go
- handlers/memcached/std/handler.go
- handlers/memcached/std/localComm.go
- orcas/l1l2.go
- orcas/l1only.go
- orcas/types.go
- server/default.go
- server/listen.go
- server/types.go
- server/utils.go
This is the final PR for the L1/L2 functionality. This includes full support for L1/L2 interactions with the same API as the standard memcached-backed L1 only scheme. It does assume an L2 server that is also running rend (for now) because we use the GetE command to retrieve the expiration time from L2 along with the data when we need it. This is an extension to the memcached protocol that we use to be more efficient with our implementation.
CC @vuzilla @senugula for review
> Multilevel support (a.k.a. Refactor level 4)

- handlers/memcached/chunked/handler.go
- handlers/memcached/chunked/keys.go
- handlers/memcached/chunked/types.go
The previous implementation took a fixed data size of 1024 bytes, which
would spill over to another slab if the key was too long. Now the
overhead of memcached metadata and key length are taken into account
when chunking data so there is no space wastage and everything stays in
the same slab.
In other words the data now fits *just* right.
Fixes #57 
CC @vuzilla @senugula @smadappa for review
> Calculating data chunk size based on memcached overhead and key size

- NOTICE
- metrics/endpoint.go
- metrics/histograms.go
- metrics/lzcnt.go
- metrics/lzcnt_amd64.s
- metrics/lzcnt_asm.go
- metrics/lzcnt_test.go
- server/types.go
Two things for histograms in this PR:
1) Adding an option to sample or not in the regular histograms, since some operations are much higher traffic than others. get and get-and-touch are sampled at 25% while the rest are not.
Closes #37 
2) Bucketized histograms. These are standardized power-of-two buckets for the full range of the 64 bit unsigned integer space. These are reported alongside the original histograms because the aggregate better across a whole fleet of servers. They are less accurate in terms of percentiles, however.
Closes #55
> Histogram improvements

- handlers/memcached/chunked/keys.go
- handlers/memcached/chunked/types.go
- memproxy.go
- orcas/l1l2batch.go
- orcas/types.go
- textprot/parser.go
- textprot/respond.go
This adds a new external port (11212 by default) and a new orca that behaves differently than the standard L1/L2 implementation. This is primarily for use by the offline batch compute systems at Netflix, which will compute and load data into caches in large quantities with specific behaviors. This batch endpoint is an attempt to separate that offline system behavior from the online one, primarily by focusing on L2 as the source of truth and generally invalidating L1 if anything changes instead of attempting to reconcile both.
CC @vuzilla @senugula @smadappa for review
> L1l2 batch orchestrator

- client/binprot/headers.go
- client/binprot/prot.go
- client/setget.go
- memproxy.go
- orcas/locked.go
- orcas/locking.go
This introduces a wrapper orchestrator that will apply locking to the operations based on the key. It is configurable to have either sync.Mutex or sync.RWMutex semantics, the former of which is enforced if using data chunking. By default it
* is off
* uses RWMutex semantics
* allows 256 parallel operations at the same time (infinite readers)
CC @vuzilla @senugula @smadappa for review
> Locking orcas

- handlers/types.go
- memproxy.go
This PR closes #72 
The extraneous type was useless and had some code smell associated with it. It's gone now, along with its extraneous function call cousin.
> Removing handlers.HandlerConstConst

- handlers/memcached/chunked/handler.go
This change is to address large values in chunked mode.
For each value in a chunked get request, we write the header to the socket. Previously, this was through a buffered writer. For requests that generated more than 4k of headers, we would write into the bufio buffer, flush (implicitly, when it gets full), write, flush, write, flush, etc. This change instead buffers all of the headers for an individual chunked get request into one big buffer before sending via `bufio.Writer.ReadFrom()`. This will directly write all of the headers at once, avoiding the multiple flushes, each of which cause a `write()` syscall to send to the unix domain socket fd.
Unfortunately, this doesn't completely solve the problem it was meant to address. We were seeing memcached connection yields for these large …
> Large batch get optimization

- client/sizes.go
Previously it was passed by value, meaning the program would never stop.
Closes #78 
CC @smadappa @vuzilla @senugula @akpratt 
and @dgryski
> Passing sync.WaitGroup by reference in client sizes testing program

- orcas/l1l2batch.go
- orcas/types.go
This tweaks the behavior of the L1/L2 batch orchestrator to more actively manage the hot data in L1 vs. deleting on any change. This keeps hot data hot even if it is changed out from under the member watching Netflix at the time. Large batch computes would otherwise cause all hot data to be evicted from L1 anyway, which was the point of having a different port and orchestrator to begin with. 
Closes #74 
CC @vuzilla @senugula @smadappa @akpratt for review
> Rework batch port operations to more actively manage L1

- orcas/l1l2.go
- orcas/types.go
This is a change to help internal transitions and deployments. It allows L2 to have more control over what it wants to do with the touches. It does require L2 to do more disk reads in the standard scenario, but this is acceptable for our use cases.
CC @vuzilla @smadappa @senugula @akpratt
> Changing standard port GAT to touch L2 on L1 GAT hit instead of set

- metrics/endpoint.go
- metrics/histograms.go
- orcas/l1l2.go
- orcas/l1l2batch.go
- orcas/l1only.go
- orcas/types.go
This PR adds histograms to the sub-operations that combine to make up an overall operation. For example, a get operation overall may be comprised of a get in L1, a get in L2, and a set in L1. Right now the only metrics we have are for the overall operations. In order to gain better insight, we will now have timing information on L1 and L2 individual operations.
This does add some additional memory use, but it's only a few megabytes (and in large chunks) so it's not a big deal.
closes #66 
CC @smadappa @vuzilla @senugula @akpratt for review
> Sub op histograms

- metrics/endpoint.go
- metrics/histograms.go
Removing a ton of unnecessary pointers in the process as well.
Closes #62 
CC @smadappa @vuzilla @senugula @akpratt for review
> metrics: Changing histogram buckets to match spectator library.

- orcas/l1l2batch.go
Under high load, rend would receive SETQ calls, which do not expect a response. When the client got a response, it assumed a problem and disconnected. This is exactly the worst thing to do under heavy load as it requires clients to reconnect, which takes even longer. This change removes the erroneous erasure of the quiet flag.
Closes #94 
CC @vuzilla @smadappa @senugula @akpratt for review
> Removing req.Quiet changes in the L1L2Batch orchestrator.

- server/listen.go
Sometimes we see Rend not able to bind to a port. This change causes the process to crash intentionally if that happens, along with providing information that should have been printed before but wasn't.
Closes #98 
CC @vuzilla @smadappa @senugula @akpratt
> Server listener now panics if it can't bind to the port.

- common/datatypes.go
- orcas/locked.go
- orcas/locked_test.go
- server/default.go
- server/default_test.go
This fixes the locking orchestrator to guarantee that unlocks happen in the case of a panic in the wrapped orchestrator.
Closes #105 
CC @vuzilla @smadappa @senugula for review
> 105 guarantee unlocks

- client/textprot/prot.go
Hi !
I was testing my custom handler then I spotted a weird bug :)
```
> go run setget.go -p 11211 -w 1 -n 1
2017/02/09 10:50:42 Done generating keys
Connected to memcached.
Setting key AAAB to value of length 8101
STORED
Set key AAAB
Getting key AAAB
VALUE AAAB 0 8101
ZJQFS
[...]
LOXFW
END
Got key AAAB
return = [69 78 68 13 10] --> "END\CR\LF"
2017/02/09 10:50:42 Data returned from server does not match! 
Data len sent: 8101 
Data len recv: 5
2017/02/09 10:50:42 Total comm time: 3421833
```
This patch should make textprot Get function return what is expected (trimmed value)
Thanks for your work !
> fix : client textprot Get always return "END\r\n"

- .travis.yml
The default options for Go projects might be sufficient as per instructions.
This config simply adds the setting to use the most-recent Linux distro
available on Travis CI (Trusty) and disables `sudo` to use the more efficient
container-based infrastructure.
Additional customizations can be added once this config is enabled and it's easy
to test new iterations via the GitHub PR mechanism, which will get Travis to
test each PR automatically.
Note that a repo admin needs to activate this repo on Travis CI by going to this page:
https://travis-ci.org/Netflix/rend
> Add .travis.yml config for Travis CI support.

- .travis.yml
- binprot/parser_test.go
The rend project uses all lowercase import paths even though the Netflix GitHub org is "Netflix"
This changes the import path used on the travis build system to match the lowercase paths.
> Change travis import path to match lowercase "netflix"

- metrics/counters.go
- orcas/l1l2.go
- orcas/l1l2_test.go
- orcas/l1l2batch.go
- orcas/l1l2batch_test.go
- orcas/types.go
- orcas/util_test.go
Previously, things like an out of memory error may mean that there is an inconsistent state in L1 after a set operation. On any kind of error during a set operation a delete will be sent to L1 afterwards and the operation will succeed even though L1 had an error.
This PR is the beginning of fixing #102
> Better handling of problematic sets

- handlers/memcached/batched/conn.go
- handlers/memcached/batched/handler.go
- handlers/memcached/batched/relay.go
- handlers/memcached/batched/types.go
This change adds error handling to the batching connection handler to recover when memcached crashes or is killed. This was a somewhat large change as most things needed to gain some extra retry logic.
> Batching connection fix

- memproxy.go
- server/listen.go
- server/types.go
There is an internal need for Netflix to allow a listener that has a more complex setup, e.g. internal authentication mechanisms. This refactor allows a user of the libraries to replace the socket bind with whatever mechanism they deem fit.
> Refactor listener in server to allow for more complex listeners

- server/listen.go
- server/types.go
I figured out that some types of connection configurations require returning a wrapped connection, so this interface change adds a return value for the connection along with the error. I also decided (based on previous feedback) that the name ModifyConnSettings was a little verbose and too specific, so that's been changed to Configure.
> Updating interface for server.Listener to support wrapped connections
